FROM node:16.16.0 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install 
RUN npm install react-scripts@5.0.1 -g 
RUN sudo apt install docker-compose

COPY . /usr/src/app
RUN npm run build

FROM nginx:1.18.0
# nginx의 기본 설정을 삭제하고 앱에서 설정한 파일을 복사
# RUN rm -rf /etc/nginx/conf.d
# COPY ./nginx.conf /etc/nginx/conf.d
COPY /test.conf /etc/nginx/sites-available/test.conf 

# 위에서 생성한 앱의 빌드산출물을 nginx의 샘플 앱이 사용하던 폴더로 이동
COPY --from=builder /usr/share/nginx/html /usr/src/app/build

# 80포트 오픈하고 nginx 실행
EXPOSE 80
# EXPOSE 3000
# 로컬에 있는 default.conf 파일을 도커 /etc/nginx/conf.d/defalut.conf로 복사
CMD ["nginx", "-g", "daemon off;"]